import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Voltex Design System Colors
        'on-primary': '#00363d',
        'secondary': '#b3c5ff',
        'on-surface-variant': '#bac9cc',
        'secondary-fixed-dim': '#b3c5ff',
        'surface-container-low': '#191b24',
        'primary': '#c3f5ff',
        'secondary-container': '#0266ff',
        'surface-container-lowest': '#0b0e16',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#005228',
        'on-error': '#690005',
        'surface': '#060810',
        'on-secondary-container': '#f9f7ff',
        'on-primary-fixed': '#001f24',
        'on-secondary-fixed': '#001849',
        'surface-dim': '#11131c',
        'surface-tint': '#00daf3',
        'background': '#060810',
        'surface-container-high': '#272a33',
        'on-primary-container': '#00626e',
        'on-tertiary': '#003919',
        'on-primary-fixed-variant': '#004f58',
        'tertiary-fixed': '#60ff99',
        'primary-fixed-dim': '#00daf3',
        'on-background': '#e1e1ee',
        'tertiary-container': '#00ef7f',
        'on-secondary-fixed-variant': '#003fa4',
        'surface-bright': '#373942',
        'inverse-on-surface': '#2e3039',
        'outline-variant': '#3b494c',
        'tertiary-fixed-dim': '#00e479',
        'primary-container': '#00e5ff',
        'inverse-surface': '#e1e1ee',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#9cf0ff',
        'on-tertiary-fixed': '#00210c',
        'on-surface': '#e1e1ee',
        'on-tertiary-container': '#006733',
        'error': '#ffb4ab',
        'surface-container-highest': '#32343e',
        'tertiary': '#aeffbf',
        'surface-container': '#1d1f28',
        'outline': '#849396',
        'inverse-primary': '#006875',
        'secondary-fixed': '#dae1ff',
        'on-secondary': '#002b75',
        'surface-variant': '#32343e',
      },
      fontFamily: {
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Space Grotesk', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'syne': ['Syne', 'sans-serif'],
        'bebas': ['Bebas Neue', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0rem',
        'lg': '0rem',
        'xl': '0rem',
        'full': '9999px',
      },
      letterSpacing: {
        'tightest': '-0.04em',
        'tech': '0.15rem',
        'wide-tech': '0.3rem',
        'ultra-wide': '0.5rem',
      },
    },
  },
  plugins: [],
}
export default config
